apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-fgnh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-fgnh
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-fgnh
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-fgnh
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-fgnh
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-yfrc-tenant/rhtap-demo-app/hacbs-test-project-fgnh@sha256:59afe60ff855f2c0152efbb2a036dd7d01c62fda863db0e57f8ccdfb97170390
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
