apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-fgnh
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-yfrc-tenant/rhtap-demo-app/hacbs-test-project-fgnh@sha256:f7dddffa93ff19ce3dd4694e5e36e352ab552021a84a3df0056f86d95e4b96d1
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
